name: Build

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  installations:
    name: Instalações gerais
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.0'

      - name: Install dependencies
        run: npm install --force

      - name: Build BackEnd
        run: npm run build:api

      - name: Build FrontEnd
        run: npm run build:front
