name: Build

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  installations:
    name: Instalações gerais
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.0'

      - name: Install dependencies
        run: npm install --force

  build-api:
    name: Build do Backend
    runs-on: ubuntu-latest
    needs: installations
    steps:
      - name: Build project
        run: npm run build:api
  build-front:
    name: Build do Front
    runs-on: ubuntu-latest
    needs: installations
    steps:
      - name: Build project
        run: npm run build:front
